#MODULE = openwsn

INCLUDES += -I$(OPENWSN_ROOT)/openapps/rrt \
			-I$(OPENWSN_ROOT)/openapps/techo \
			-I$(OPENWSN_ROOT)/openapps/uecho \
			-I$(OPENWSN_ROOT)/openapps/uinject

include $(RIOTBASE)/Makefile.base
